### PR TITLE
Added checks for non-exisiting files in classpath converters.

### PR DESCRIPTION
**Pull request by VelaSolaris**
After creating the PR, please add a commit that adds a bullet-point under the `-SNAPSHOT` section of [CHANGES.md](https://github.com/VelaSolaris/matconsolectl/blob/master/CHANGES.md) that includes:

- [x] a summary of the change
- [x] a link to the newly created PR

This makes it easier for the maintainers to quickly release your changes.

### CODE REVIEW

**Comment by VelaSolaris** [comment]
I ran spotlessApply before committing, and the build was successful on my local repo. But it still seems to fail here.

**Comment by nedtwigg** [comment]
Blast from the past!!!  Dunno why the line-endings got screwed up, but it's fixed now.  This mostly looks reasonable to me, but I've used this on a lot of machines in a lot of environments, and never bumped into this problem.  Can you describe a little about the environment that causes this problem?

**Comment by mrcjkb** [comment]
Hi, this is Marc from Vela Solaris (writing from my private account).
If I remember correctly, I encountered the problem on an environment that had invalid classpath entries.

**Comment by nedtwigg** [comment]
Published in 4.6.0

**Pull request merged**
